file_format: "1"
id: joshkeeb
name: JoshKeeb
type: shield
url: https://github.com/sefodopo/joshkeeb
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
siblings:
  - joshkeeb_left
  - joshkeeb_right
